@baseUrl = {{$dotenv KEA_URL}}
@port = {{$dotenv KEA_PORT}}
@username = {{$dotenv KEA_BASIC_AUTH_USERNAME}}
@password = {{$dotenv KEA_BASIC_AUTH_PASSWORD}}
@certPath = {{$dotenv KEA_TLS_CERT_FILE}}
@keyPath = {{$dotenv KEA_TLS_KEY_FILE}}
@caPath = {{$dotenv KEA_TLS_CA_FILE}}
@header = {{$dotenv KEA_HEADER}}

// Get lease by hardware address

### Lease4 Get By Hw Address (localhost with certs)
# @name lease4GetByHwAddressDev
POST {{baseUrl}}:{{port}}/

cert: {{certPath}}
key: {{keyPath}}
ca: {{caPath}}

{
    "command": "lease4-get-by-hw-address",
    "arguments": {
        "hw-address": "1a:1b:1c:1d:1e:1f",
        "subnet-id": 1
    }
}

### Lease4 Get By Hw Address (test with basic auth)
# @name lease4GetByHwAddressTest
POST {{baseUrl}}:{{port}}/
{{header}}
Authorization: Basic {{username}}:{{password}}

{
    "command": "lease4-get-by-hw-address",
    "arguments": {
        "hw-address": "1a:1b:1c:1d:1e:1f",
        "subnet-id": 1
    }
}
