POST https://localhost:8000/
Content-Type: application/json
cert: hack/docker/certs/client.crt
key: hack/docker/certs/client.key
ca: hack/docker/certs/ca.crt

{
    "command": "lease4-add",
    "arguments": {
    "ip-address": "10.123.0.123",
        "hw-address": "00:02:12:34:56:78",
        "subnet-id": 1
    }
}