@baseUrl = {{$dotenv KEA_URL}}
@port = {{$dotenv KEA_PORT}}
@username = {{$dotenv KEA_BASIC_AUTH_USERNAME}}
@password = {{$dotenv KEA_BASIC_AUTH_PASSWORD}}
@certPath = {{$dotenv KEA_TLS_CERT_FILE}}
@keyPath = {{$dotenv KEA_TLS_KEY_FILE}}
@caPath = {{$dotenv KEA_TLS_CA_FILE}}
@header = {{$dotenv KEA_HEADER}}

### Lease4 Add (localhost with certs)
# @name lease4AddDev
POST {{baseUrl}}:{{port}}/
{{header}}
cert: {{certPath}}
key: {{keyPath}}
ca: {{caPath}}

{
    "command": "lease4-add",
    "arguments": {
    "ip-address": "10.123.0.123",
        "hw-address": "00:02:12:34:56:78",
        "subnet-id": 1
    }
}

### Lease4 Add (test with basic auth)
# @name lease4AddTest
POST {{baseUrl}}:{{port}}/
{{header}}
Authorization: Basic {{username}}:{{password}}

{
    "command": "lease4-add",
    "arguments": {
    "ip-address": "10.123.0.123",
        "hw-address": "00:02:12:34:56:78",
        "subnet-id": 1
    }
}
