POST https://localhost:8000/
Content-Type: application/json
cert: hack/docker/certs/client.crt
key: hack/docker/certs/client.key
ca: hack/docker/certs/ca.crt

{
    "command": "lease4-get-all",
    "arguments": {
        "subnets": [1]
    }
}