@baseUrl = {{$dotenv KEA_URL}}
@port = {{$dotenv KEA_PORT}}
@username = {{$dotenv KEA_BASIC_AUTH_USERNAME}}
@password = {{$dotenv KEA_BASIC_AUTH_PASSWORD}}
@certPath = {{$dotenv KEA_TLS_CERT_FILE}}
@keyPath = {{$dotenv KEA_TLS_KEY_FILE}}
@caPath = {{$dotenv KEA_TLS_CA_FILE}}
@header = {{$dotenv KEA_HEADER}}

@macAddress = "00:02:12:34:56:78"

// Add a reservation to subnet
// The operation-target parameter accepts the following values:
// * memory - query or update the runtime server configuration
// * database - query or update host database(s)
// * all - query or update both runtime configuration and host database(s)
// * default - query or update a default host data source - it is command-specific
// Delete reservation by mac address

### Reservation Del By Mac (localhost with certs)
# @name reservationDelByMacDev
POST {{baseUrl}}:{{port}}/
{{header}}
cert: {{certPath}}
key: {{keyPath}}
ca: {{caPath}}

{
    "command": "reservation-del",
    "arguments": {
        "subnet-id": 1,
        "identifier-type": "hw-address",
        "identifier": "{{macAddress}}",
        "operation-target": "all"
    }
}

### Reservation Del By Mac (test with basic auth)
# @name reservationDelByMacTest
POST {{baseUrl}}:{{port}}/
{{header}}
Authorization: Basic {{username}}:{{password}}

{
    "command": "reservation-del",
    "arguments": {
        "subnet-id": 1,
        "identifier-type": "hw-address",
        "identifier": "{{macAddress}}",
        "operation-target": "all"
    }
}
