@baseUrl = {{$dotenv KEA_URL}}
@port = {{$dotenv KEA_PORT}}
@username = {{$dotenv KEA_BASIC_AUTH_USERNAME}}
@password = {{$dotenv KEA_BASIC_AUTH_PASSWORD}}
@certPath = {{$dotenv KEA_TLS_CERT_FILE}}
@keyPath = {{$dotenv KEA_TLS_KEY_FILE}}
@caPath = {{$dotenv KEA_TLS_CA_FILE}}
@header = {{$dotenv KEA_HEADER}}
// Get reservation by hardware address

### Reservation Get By Id (localhost with certs)
# @name reservationGetByIdDev
POST {{baseUrl}}:{{port}}/
{{header}}
cert: {{certPath}}
key: {{keyPath}}
ca: {{caPath}}

{
    "command": "reservation-get-by-id",
    "arguments": {
        "identifier-type": "hw-address",
        "identifier": "f4:03:43:ea:eb:10"
     }
 }

### Reservation Get By Id (test with basic auth)
# @name reservationGetByIdTest
POST {{baseUrl}}:{{port}}/
{{header}}
Authorization: Basic {{username}}:{{password}}

{
    "command": "reservation-get-by-id",
    "arguments": {
        "identifier-type": "hw-address",
        "identifier": "f4:03:43:ea:eb:10"
     }
 }
