POST https://localhost:8000/
Content-Type: application/json
cert: hack/docker/certs/client.crt
key: hack/docker/certs/client.key
ca: hack/docker/certs/ca.crt

// Get all reservations in a subnet

{
    "command": "reservation-get-all",
    "arguments": {
        "subnet-id": 1
     }
}