@baseUrl = {{$dotenv KEA_URL}}
@port = {{$dotenv KEA_PORT}}
@username = {{$dotenv KEA_BASIC_AUTH_USERNAME}}
@password = {{$dotenv KEA_BASIC_AUTH_PASSWORD}}
@certPath = {{$dotenv KEA_TLS_CERT_FILE}}
@keyPath = {{$dotenv KEA_TLS_KEY_FILE}}
@caPath = {{$dotenv KEA_TLS_CA_FILE}}
@header = {{$dotenv KEA_HEADER}}

@subnetId = 1

### Get all reservations in a subnet (localhost with certs)
# @name getAllReservationsDev
POST {{baseUrl}}:{{port}}/
{{header}}
cert: {{certPath}}
key: {{keyPath}}
ca: {{caPath}}

{
    "command": "reservation-get-all",
    "arguments": {
        "subnet-id": {{subnetId}}
     }
}

### Get all reservations in a subnet (test with basic auth)
# @name getAllReservationsTest
POST {{baseUrl}}:{{port}}/
{{header}}
Authorization: Basic {{username}}:{{password}}

{
    "command": "reservation-get-all",
    "arguments": {
        "subnet-id": {{subnetId}}
     }
}