POST https://localhost:8000/
Content-Type: application/json
cert: hack/docker/certs/client.crt
key: hack/docker/certs/client.key
ca: hack/docker/certs/ca.crt

    {
      "command": "config-set",
      "arguments": {
        "Dhcp4": {
          "subnet4": [
            {
              "id": 1,
              "subnet": "192.0.2.0/24",
              "pools": [
                {
                  "pool": "192.0.2.1 - 192.0.2.200"
                }
              ],
              "option-data": [
                {
                  "name": "domain-name-servers",
                  "space": "dhcp4",
                  "data": "192.0.3.1,192.0.3.2"
                }
              ]
            }
            // Add other subnets if necessary
          ]
        }
      }
    }