POST https://localhost:8000/
Content-Type: application/json
cert: hack/docker/certs/client.crt
key: hack/docker/certs/client.key
ca: hack/docker/certs/ca.crt

{
    "command": "subnet4-add",
    "arguments": {
        "subnet4": [ {
            "id": 2,
            "subnet": "10.123.1.0/24",
            "option-data": [
                { "name": "routers",
                  "data": "10.123.1.1"
               }
            ],
            "pools": [
                {
                  "pool": "10.123.1.4-10.123.1.254",
                  "require-client-classes": [
                  "biosclients",
                  "ueficlients",
                  "ipxeclients"
                  ]
                }
            ]
        } ]
    }
}