@baseUrl = {{$dotenv KEA_URL}}
@port = {{$dotenv KEA_PORT}}
@username = {{$dotenv KEA_BASIC_AUTH_USERNAME}}
@password = {{$dotenv KEA_BASIC_AUTH_PASSWORD}}
@certPath = {{$dotenv KEA_TLS_CERT_FILE}}
@keyPath = {{$dotenv KEA_TLS_KEY_FILE}}
@caPath = {{$dotenv KEA_TLS_CA_FILE}}
@header = {{$dotenv KEA_HEADER}}

### Subnet4 Update (localhost with certs)
# @name subnet4UpdateDev
POST {{baseUrl}}:{{port}}/
{{header}}
cert: {{certPath}}
key: {{keyPath}}
ca: {{caPath}}

{
  "command": "subnet4-update", 
  "arguments": {
     "subnet4": [{
        "id": 2,
  "subnet": "10.123.2.0/24"
      }]
  }
}

### Subnet4 Update (test with basic auth)
# @name subnet4UpdateTest
POST {{baseUrl}}:{{port}}/
{{header}}
Authorization: Basic {{username}}:{{password}}

{
  "command": "subnet4-update", 
  "arguments": {
     "subnet4": [{
        "id": 2,
  "subnet": "10.123.2.0/24"
      }]
  }
}
