@baseUrl = {{$dotenv KEA_URL}}
@port = {{$dotenv KEA_PORT}}
@username = {{$dotenv KEA_BASIC_AUTH_USERNAME}}
@password = {{$dotenv KEA_BASIC_AUTH_PASSWORD}}
@certPath = {{$dotenv KEA_TLS_CERT_FILE}}
@keyPath = {{$dotenv KEA_TLS_KEY_FILE}}
@caPath = {{$dotenv KEA_TLS_CA_FILE}}
@header = {{$dotenv KEA_HEADER}}

// To retrieve detailed information about the subnet, use the subnet4-get command with the subnet ID.

### Subnet4 Get (localhost with certs)
# @name subnet4GetDev
POST {{baseUrl}}:{{port}}/
{{header}}
cert: {{certPath}}
key: {{keyPath}}
ca: {{caPath}}

{
  "command": "subnet4-get", 
  "arguments": {
    "id": 1
  }
}

### Subnet4 Get (test with basic auth)
# @name subnet4GetTest
POST {{baseUrl}}:{{port}}/
{{header}}
Authorization: Basic {{username}}:{{password}}

{
  "command": "subnet4-get", 
  "arguments": {
    "id": 1
  }
}
