POST https://localhost:8000/
Content-Type: application/json
cert: hack/docker/certs/client.crt
key: hack/docker/certs/client.key
ca: hack/docker/certs/ca.crt

{
  "command": "subnet4-update", 
  "arguments": {
     "subnet4": [{
        "id": 2,
  "subnet": "10.123.2.0/24"
      }]
  }
}