package consts

const (
	JSON_LOGGING = "JSON_LOGGING"
	LOG_LEVEL    = "LOG_LEVEL"

	KEA_BASE_URL        = "KEA_BASE_URL"
	KEA_HOST            = "KEA_HOST"
	KEA_PORT            = "KEA_PORT"
	KEA_TLS_CA_FILE     = "KEA_TLS_CA_FILE"
	KEA_TLS_CERT_FILE   = "KEA_TLS_CERT_FILE"
	KEA_TLS_KEY_FILE    = "KEA_TLS_KEY_FILE"
	KEA_TLS_INSECURE    = "KEA_TLS_INSECURE"
	KEA_TLS_SERVER_NAME = "KEA_TLS_SERVER_NAME"
	KEA_TIMEOUT_SECONDS = "KEA_TIMEOUT_SECONDS"
)
